# Generated by Django 4.2.7 on 2023-11-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_clave', models.PositiveIntegerField(unique=True)),
                ('usuario_nombre', models.CharField(max_length=20, unique=True)),
                ('usuario_apellido', models.CharField(max_length=20)),
                ('usuario_correo', models.EmailField(max_length=254, unique=True)),
                ('usuario_contrasena', models.CharField(max_length=255)),
                ('usuario_foto_rostro', models.CharField(blank=True, max_length=55, null=True)),
                ('usuario_modo_registro', models.CharField(blank=True, default='correo', max_length=25, null=True)),
                ('usuario_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_role', models.IntegerField(default=1)),
                ('usuario_estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
