# Generated by Django 4.2.7 on 2023-11-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True, default='Descripción de la Suscripción', null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photos')),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-id'],
            },
        ),
    ]
