# Generated by Django 4.2.7 on 2023-11-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_clave', models.PositiveIntegerField(unique=True)),
                ('rol_nombre', models.CharField(max_length=20, unique=True)),
                ('rol_fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('rol_activa', models.IntegerField(default=1)),
                ('rol_estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
